[2024-09-15 20:04:00,372] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:04:00,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:04:00,376] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:00,376] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:00,376] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:00,386] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-13 00:00:00+00:00
[2024-09-15 20:04:00,388] {standard_task_runner.py:52} INFO - Started process 11459 to run task
[2024-09-15 20:04:00,390] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-13T00:00:00+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpmp5sywj9', '--error-file', '/tmp/tmpyxiwwads']
[2024-09-15 20:04:00,391] {standard_task_runner.py:80} INFO - Job 46: Subtask BRONZE_MSFT
[2024-09-15 20:04:00,417] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:00,454] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-13T00:00:00+00:00
[2024-09-15 20:04:00,455] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:00,457] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240113T000000, start_date=20240915T230400, end_date=20240915T230400
[2024-09-15 20:04:00,467] {standard_task_runner.py:92} ERROR - Failed to execute job 46 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 11459)
[2024-09-15 20:04:00,483] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:00,492] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:45,588] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:06:45,592] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:06:45,592] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:45,592] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:45,592] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:45,603] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-13 00:00:00+00:00
[2024-09-15 20:06:45,605] {standard_task_runner.py:52} INFO - Started process 12171 to run task
[2024-09-15 20:06:45,607] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-13T00:00:00+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpnmmbeepb', '--error-file', '/tmp/tmpg1k793vo']
[2024-09-15 20:06:45,607] {standard_task_runner.py:80} INFO - Job 48: Subtask BRONZE_MSFT
[2024-09-15 20:06:45,633] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:45,673] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-13T00:00:00+00:00
[2024-09-15 20:06:45,674] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:45,677] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240113T000000, start_date=20240915T230645, end_date=20240915T230645
[2024-09-15 20:06:45,685] {standard_task_runner.py:92} ERROR - Failed to execute job 48 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 12171)
[2024-09-15 20:06:45,700] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:45,721] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:10:45,755] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:10:45,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:10:45,759] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:10:45,759] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:10:45,759] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:10:45,769] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-13 00:00:00+00:00
[2024-09-15 20:10:45,772] {standard_task_runner.py:52} INFO - Started process 12781 to run task
[2024-09-15 20:10:45,774] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-13T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpd6wsra3e', '--error-file', '/tmp/tmpewi68znt']
[2024-09-15 20:10:45,774] {standard_task_runner.py:80} INFO - Job 97: Subtask BRONZE_MSFT
[2024-09-15 20:10:45,804] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:10:45,860] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-13T00:00:00+00:00
[2024-09-15 20:10:50,307] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-10 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704862800, endDate = 1704258000")
[2024-09-15 20:10:50,316] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:10:50,329] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240113T000000, start_date=20240915T231045, end_date=20240915T231050
[2024-09-15 20:10:50,376] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:10:50,389] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:13:22,247] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:13:22,254] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:13:22,254] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:22,255] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:13:22,255] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:22,266] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-13 00:00:00+00:00
[2024-09-15 20:13:22,269] {standard_task_runner.py:52} INFO - Started process 13390 to run task
[2024-09-15 20:13:22,271] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-13T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpf5hk9m65', '--error-file', '/tmp/tmp9hsk7gwo']
[2024-09-15 20:13:22,272] {standard_task_runner.py:80} INFO - Job 97: Subtask BRONZE_MSFT
[2024-09-15 20:13:22,299] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:13:22,336] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-13T00:00:00+00:00
[2024-09-15 20:13:22,337] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:13:22,339] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240113T000000, start_date=20240915T231322, end_date=20240915T231322
[2024-09-15 20:13:22,348] {standard_task_runner.py:92} ERROR - Failed to execute job 97 for task BRONZE_MSFT ([Errno 13] Permission denied: '/Documents'; 13390)
[2024-09-15 20:13:22,364] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:13:22,373] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:17:42,995] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:17:43,000] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [queued]>
[2024-09-15 20:17:43,000] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:17:43,000] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:17:43,000] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:17:43,011] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-13 00:00:00+00:00
[2024-09-15 20:17:43,013] {standard_task_runner.py:52} INFO - Started process 14051 to run task
[2024-09-15 20:17:43,015] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-13T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpv6md77ij', '--error-file', '/tmp/tmptn782jst']
[2024-09-15 20:17:43,016] {standard_task_runner.py:80} INFO - Job 97: Subtask BRONZE_MSFT
[2024-09-15 20:17:43,047] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-13T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:17:43,090] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-13T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-13T00:00:00+00:00
[2024-09-15 20:17:46,255] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-10 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704862800, endDate = 1704258000")
[2024-09-15 20:17:46,263] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:17:46,271] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240113T000000, start_date=20240915T231742, end_date=20240915T231746
[2024-09-15 20:17:46,295] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:17:46,305] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
