[2024-09-15 20:04:13,850] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:04:13,854] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:04:13,854] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:13,854] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:13,854] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:13,864] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:04:13,866] {standard_task_runner.py:52} INFO - Started process 11549 to run task
[2024-09-15 20:04:13,868] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpx0834bld', '--error-file', '/tmp/tmpv8ck412d']
[2024-09-15 20:04:13,869] {standard_task_runner.py:80} INFO - Job 56: Subtask BRONZE_TSLA
[2024-09-15 20:04:13,897] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:13,936] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:04:13,936] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:13,939] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240117T000000, start_date=20240915T230413, end_date=20240915T230413
[2024-09-15 20:04:13,949] {standard_task_runner.py:92} ERROR - Failed to execute job 56 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 11549)
[2024-09-15 20:04:13,961] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:13,970] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:07:34,009] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:07:34,013] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:07:34,013] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:34,013] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:07:34,013] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:34,024] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:07:34,026] {standard_task_runner.py:52} INFO - Started process 12366 to run task
[2024-09-15 20:07:34,028] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp3_n3dyf0', '--error-file', '/tmp/tmpi377zqdl']
[2024-09-15 20:07:34,029] {standard_task_runner.py:80} INFO - Job 63: Subtask BRONZE_TSLA
[2024-09-15 20:07:34,055] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:07:34,094] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:07:37,415] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-14 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705208400, endDate = 1704258000")
[2024-09-15 20:07:37,417] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:07:37,422] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240117T000000, start_date=20240915T230734, end_date=20240915T230737
[2024-09-15 20:07:37,465] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:07:37,476] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:11:12,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:11:12,964] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:11:12,965] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:12,965] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:12,965] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:12,975] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:11:12,978] {standard_task_runner.py:52} INFO - Started process 12876 to run task
[2024-09-15 20:11:12,980] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdwzl684y', '--error-file', '/tmp/tmpnbma_v3s']
[2024-09-15 20:11:12,980] {standard_task_runner.py:80} INFO - Job 107: Subtask BRONZE_TSLA
[2024-09-15 20:11:13,008] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:13,048] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:11:13,049] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:11:13,051] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240117T000000, start_date=20240915T231112, end_date=20240915T231113
[2024-09-15 20:11:13,059] {standard_task_runner.py:92} ERROR - Failed to execute job 107 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 12876)
[2024-09-15 20:11:13,073] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:11:13,082] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:13:36,094] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:13:36,099] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:13:36,099] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:36,099] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:13:36,099] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:36,109] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:13:36,112] {standard_task_runner.py:52} INFO - Started process 13480 to run task
[2024-09-15 20:13:36,114] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpv1gqhwh1', '--error-file', '/tmp/tmpzkf4mqoo']
[2024-09-15 20:13:36,115] {standard_task_runner.py:80} INFO - Job 107: Subtask BRONZE_TSLA
[2024-09-15 20:13:36,142] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:13:36,181] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:13:36,182] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:13:36,184] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240117T000000, start_date=20240915T231336, end_date=20240915T231336
[2024-09-15 20:13:36,193] {standard_task_runner.py:92} ERROR - Failed to execute job 107 for task BRONZE_TSLA ([Errno 13] Permission denied: '/Documents'; 13480)
[2024-09-15 20:13:36,207] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:13:36,216] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:18:33,880] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:18:33,885] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:18:33,885] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:33,885] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:18:33,886] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:33,897] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:18:33,900] {standard_task_runner.py:52} INFO - Started process 14142 to run task
[2024-09-15 20:18:33,902] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpi8b_d8ku', '--error-file', '/tmp/tmpbjrp7jfh']
[2024-09-15 20:18:33,902] {standard_task_runner.py:80} INFO - Job 107: Subtask BRONZE_TSLA
[2024-09-15 20:18:33,931] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:18:33,971] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:18:37,918] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-14 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705208400, endDate = 1704258000")
[2024-09-15 20:18:37,922] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:18:37,930] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240117T000000, start_date=20240915T231833, end_date=20240915T231837
[2024-09-15 20:18:37,948] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:18:37,959] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
