[2024-09-15 20:04:21,771] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:04:21,775] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:04:21,775] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:21,775] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:21,775] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:21,784] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-19 00:00:00+00:00
[2024-09-15 20:04:21,787] {standard_task_runner.py:52} INFO - Started process 11604 to run task
[2024-09-15 20:04:21,789] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp2g37rk0w', '--error-file', '/tmp/tmpmxnn230a']
[2024-09-15 20:04:21,789] {standard_task_runner.py:80} INFO - Job 62: Subtask BRONZE_MSFT
[2024-09-15 20:04:21,817] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:21,856] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-09-15 20:04:21,857] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:21,860] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240119T000000, start_date=20240915T230421, end_date=20240915T230421
[2024-09-15 20:04:21,868] {standard_task_runner.py:92} ERROR - Failed to execute job 62 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 11604)
[2024-09-15 20:04:21,881] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:21,891] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:11:22,295] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:11:22,300] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:11:22,300] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:22,300] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:22,300] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:22,312] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-19 00:00:00+00:00
[2024-09-15 20:11:22,314] {standard_task_runner.py:52} INFO - Started process 12931 to run task
[2024-09-15 20:11:22,316] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpqpffgu88', '--error-file', '/tmp/tmpk0iy0sm2']
[2024-09-15 20:11:22,317] {standard_task_runner.py:80} INFO - Job 113: Subtask BRONZE_MSFT
[2024-09-15 20:11:22,345] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:22,388] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-09-15 20:11:22,389] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:11:22,391] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240119T000000, start_date=20240915T231122, end_date=20240915T231122
[2024-09-15 20:11:22,400] {standard_task_runner.py:92} ERROR - Failed to execute job 113 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 12931)
[2024-09-15 20:11:22,409] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:11:22,418] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:19:05,863] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:19:05,867] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-09-15 20:19:05,867] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:19:05,867] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:19:05,867] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:19:05,878] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-19 00:00:00+00:00
[2024-09-15 20:19:05,880] {standard_task_runner.py:52} INFO - Started process 14197 to run task
[2024-09-15 20:19:05,882] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmptlfjqjx6', '--error-file', '/tmp/tmp_ftnbe1l']
[2024-09-15 20:19:05,883] {standard_task_runner.py:80} INFO - Job 113: Subtask BRONZE_MSFT
[2024-09-15 20:19:05,914] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-19T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:19:05,958] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-19T00:00:00+00:00
[2024-09-15 20:19:09,610] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-16 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705381200, endDate = 1704258000")
[2024-09-15 20:19:09,619] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:19:09,628] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240119T000000, start_date=20240915T231905, end_date=20240915T231909
[2024-09-15 20:19:09,646] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:19:09,657] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
