[2024-09-15 20:03:15,098] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:03:15,103] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:03:15,103] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:15,103] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:03:15,103] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:15,113] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:03:15,115] {standard_task_runner.py:52} INFO - Started process 11297 to run task
[2024-09-15 20:03:15,117] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpn18u4b0y', '--error-file', '/tmp/tmpfhhx2r3x']
[2024-09-15 20:03:15,118] {standard_task_runner.py:80} INFO - Job 29: Subtask BRONZE_AAPL
[2024-09-15 20:03:15,145] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:03:15,182] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:03:18,357] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-08 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704690000, endDate = 1704258000")
[2024-09-15 20:03:18,359] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:03:18,363] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240109T000000, start_date=20240915T230315, end_date=20240915T230318
[2024-09-15 20:03:18,389] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:03:18,399] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:21,260] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:06:21,264] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:06:21,264] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:21,264] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:21,264] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:21,275] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:06:21,277] {standard_task_runner.py:52} INFO - Started process 12015 to run task
[2024-09-15 20:06:21,279] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpirpspub1', '--error-file', '/tmp/tmpdecrkm1c']
[2024-09-15 20:06:21,279] {standard_task_runner.py:80} INFO - Job 31: Subtask BRONZE_AAPL
[2024-09-15 20:06:21,306] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:21,345] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:06:21,346] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:21,348] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240109T000000, start_date=20240915T230621, end_date=20240915T230621
[2024-09-15 20:06:21,357] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task BRONZE_AAPL ([Errno 13] Permission denied: '/datalake'; 12015)
[2024-09-15 20:06:21,372] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:21,381] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:16,661] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:09:16,666] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:09:16,666] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:16,666] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:16,666] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:16,679] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:09:16,681] {standard_task_runner.py:52} INFO - Started process 12608 to run task
[2024-09-15 20:09:16,683] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpdrf4f1kb', '--error-file', '/tmp/tmps6ofhfmx']
[2024-09-15 20:09:16,684] {standard_task_runner.py:80} INFO - Job 80: Subtask BRONZE_AAPL
[2024-09-15 20:09:16,713] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:16,752] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:09:19,894] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-06 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704517200, endDate = 1704258000")
[2024-09-15 20:09:19,896] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:19,900] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240109T000000, start_date=20240915T230916, end_date=20240915T230919
[2024-09-15 20:09:19,914] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:19,925] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:56,979] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:12:56,983] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:12:56,983] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:56,983] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:56,983] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:56,994] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:12:56,997] {standard_task_runner.py:52} INFO - Started process 13235 to run task
[2024-09-15 20:12:56,999] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpr39t2z77', '--error-file', '/tmp/tmprk66cyfd']
[2024-09-15 20:12:57,000] {standard_task_runner.py:80} INFO - Job 80: Subtask BRONZE_AAPL
[2024-09-15 20:12:57,032] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:57,074] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:12:57,075] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/AAPL'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:57,078] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240109T000000, start_date=20240915T231256, end_date=20240915T231257
[2024-09-15 20:12:57,087] {standard_task_runner.py:92} ERROR - Failed to execute job 80 for task BRONZE_AAPL ([Errno 13] Permission denied: '/Documents'; 13235)
[2024-09-15 20:12:57,092] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:57,103] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:15,939] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:16:15,943] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:16:15,943] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:15,943] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:15,943] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:15,954] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_AAPL> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:16:15,958] {standard_task_runner.py:52} INFO - Started process 13887 to run task
[2024-09-15 20:16:15,963] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_AAPL', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpxmqu8pkg', '--error-file', '/tmp/tmpqvgkbcd4']
[2024-09-15 20:16:15,964] {standard_task_runner.py:80} INFO - Job 80: Subtask BRONZE_AAPL
[2024-09-15 20:16:15,997] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_AAPL scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:16,034] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_AAPL
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:16:19,783] {history.py:244} ERROR - $AAPL: possibly delisted; no price data found  (1h 2024-01-06 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704517200, endDate = 1704258000")
[2024-09-15 20:16:19,785] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:19,789] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_AAPL, execution_date=20240109T000000, start_date=20240915T231615, end_date=20240915T231619
[2024-09-15 20:16:19,837] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:19,849] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
