[2024-09-15 20:04:08,915] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:04:08,919] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:04:08,919] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:08,919] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:08,919] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:08,929] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-16 00:00:00+00:00
[2024-09-15 20:04:08,931] {standard_task_runner.py:52} INFO - Started process 11513 to run task
[2024-09-15 20:04:08,934] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp2nhilmjj', '--error-file', '/tmp/tmprisfse9k']
[2024-09-15 20:04:08,934] {standard_task_runner.py:80} INFO - Job 52: Subtask BRONZE_TSLA
[2024-09-15 20:04:08,961] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:09,000] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-09-15 20:04:09,001] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:09,003] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240116T000000, start_date=20240915T230408, end_date=20240915T230409
[2024-09-15 20:04:09,012] {standard_task_runner.py:92} ERROR - Failed to execute job 52 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 11513)
[2024-09-15 20:04:09,026] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:09,036] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:07:02,040] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:07:02,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:07:02,045] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:02,045] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:07:02,045] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:02,055] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-16 00:00:00+00:00
[2024-09-15 20:07:02,057] {standard_task_runner.py:52} INFO - Started process 12229 to run task
[2024-09-15 20:07:02,060] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpzfus4se1', '--error-file', '/tmp/tmpug9tlnft']
[2024-09-15 20:07:02,060] {standard_task_runner.py:80} INFO - Job 54: Subtask BRONZE_TSLA
[2024-09-15 20:07:02,088] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:07:02,127] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-09-15 20:07:04,236] {process_utils.py:125} INFO - Sending Signals.SIGTERM to group 12229. PIDs of all processes in the group: [12229]
[2024-09-15 20:07:04,236] {process_utils.py:80} INFO - Sending the signal Signals.SIGTERM to group 12229
[2024-09-15 20:07:04,237] {taskinstance.py:1541} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-09-15 20:07:04,239] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-13 -> 2024-01-03)
[2024-09-15 20:07:04,242] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:07:04,247] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240116T000000, start_date=20240915T230702, end_date=20240915T230704
[2024-09-15 20:07:04,263] {process_utils.py:75} INFO - Process psutil.Process(pid=12229, status='terminated', exitcode=0, started='20:07:01') (12229) terminated with exit code 0
[2024-09-15 20:11:07,694] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:11:07,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:11:07,699] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:07,699] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:07,699] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:07,709] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-16 00:00:00+00:00
[2024-09-15 20:11:07,712] {standard_task_runner.py:52} INFO - Started process 12840 to run task
[2024-09-15 20:11:07,715] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpc5p5y8vs', '--error-file', '/tmp/tmpt6inos2s']
[2024-09-15 20:11:07,715] {standard_task_runner.py:80} INFO - Job 103: Subtask BRONZE_TSLA
[2024-09-15 20:11:07,745] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:07,795] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-09-15 20:11:07,796] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:11:07,799] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240116T000000, start_date=20240915T231107, end_date=20240915T231107
[2024-09-15 20:11:07,819] {standard_task_runner.py:92} ERROR - Failed to execute job 103 for task BRONZE_TSLA ([Errno 13] Permission denied: '/datalake'; 12840)
[2024-09-15 20:11:07,848] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:11:07,858] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:13:29,957] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:13:29,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:13:29,963] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:29,963] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:13:29,963] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:29,982] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-16 00:00:00+00:00
[2024-09-15 20:13:29,985] {standard_task_runner.py:52} INFO - Started process 13444 to run task
[2024-09-15 20:13:29,987] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp4253cuxc', '--error-file', '/tmp/tmpwt041fsx']
[2024-09-15 20:13:29,987] {standard_task_runner.py:80} INFO - Job 103: Subtask BRONZE_TSLA
[2024-09-15 20:13:30,019] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:13:30,061] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-09-15 20:13:30,062] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/TSLA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:13:30,065] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240116T000000, start_date=20240915T231329, end_date=20240915T231330
[2024-09-15 20:13:30,074] {standard_task_runner.py:92} ERROR - Failed to execute job 103 for task BRONZE_TSLA ([Errno 13] Permission denied: '/Documents'; 13444)
[2024-09-15 20:13:30,080] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:13:30,089] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:18:11,016] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:18:11,020] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [queued]>
[2024-09-15 20:18:11,020] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:11,020] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:18:11,020] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:11,032] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_TSLA> on 2024-01-16 00:00:00+00:00
[2024-09-15 20:18:11,034] {standard_task_runner.py:52} INFO - Started process 14106 to run task
[2024-09-15 20:18:11,036] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_TSLA', 'scheduled__2024-01-16T00:00:00+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpulc_8hdz', '--error-file', '/tmp/tmpwab4jiew']
[2024-09-15 20:18:11,037] {standard_task_runner.py:80} INFO - Job 103: Subtask BRONZE_TSLA
[2024-09-15 20:18:11,066] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_TSLA scheduled__2024-01-16T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:18:11,107] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_TSLA
AIRFLOW_CTX_EXECUTION_DATE=2024-01-16T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-16T00:00:00+00:00
[2024-09-15 20:18:15,458] {history.py:244} ERROR - $TSLA: possibly delisted; no price data found  (1h 2024-01-13 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705122000, endDate = 1704258000")
[2024-09-15 20:18:15,462] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:18:15,466] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_TSLA, execution_date=20240116T000000, start_date=20240915T231811, end_date=20240915T231815
[2024-09-15 20:18:15,487] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:18:15,498] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
