[2024-09-15 20:04:11,435] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:04:11,439] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:04:11,439] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:11,439] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:04:11,439] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:04:11,450] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:04:11,452] {standard_task_runner.py:52} INFO - Started process 11531 to run task
[2024-09-15 20:04:11,454] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpq7crm5de', '--error-file', '/tmp/tmpqev9bryk']
[2024-09-15 20:04:11,455] {standard_task_runner.py:80} INFO - Job 54: Subtask BRONZE_MSFT
[2024-09-15 20:04:11,483] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:04:11,525] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:04:11,526] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:04:11,530] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240117T000000, start_date=20240915T230411, end_date=20240915T230411
[2024-09-15 20:04:11,540] {standard_task_runner.py:92} ERROR - Failed to execute job 54 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 11531)
[2024-09-15 20:04:11,547] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:04:11,558] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:07:24,561] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:07:24,565] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:07:24,566] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:24,566] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:07:24,566] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:07:24,576] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:07:24,578] {standard_task_runner.py:52} INFO - Started process 12348 to run task
[2024-09-15 20:07:24,580] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp7_c6b_no', '--error-file', '/tmp/tmpul6zw0xt']
[2024-09-15 20:07:24,581] {standard_task_runner.py:80} INFO - Job 61: Subtask BRONZE_MSFT
[2024-09-15 20:07:24,607] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:07:24,645] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:07:28,338] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-14 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705208400, endDate = 1704258000")
[2024-09-15 20:07:28,346] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:07:28,356] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240117T000000, start_date=20240915T230724, end_date=20240915T230728
[2024-09-15 20:07:28,386] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:07:28,396] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:11:10,319] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:11:10,323] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:11:10,323] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:10,323] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:11:10,323] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:11:10,334] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:11:10,337] {standard_task_runner.py:52} INFO - Started process 12858 to run task
[2024-09-15 20:11:10,339] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp0kh5tjrg', '--error-file', '/tmp/tmptq81it85']
[2024-09-15 20:11:10,339] {standard_task_runner.py:80} INFO - Job 105: Subtask BRONZE_MSFT
[2024-09-15 20:11:10,369] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:11:10,407] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:11:10,408] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:11:10,411] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240117T000000, start_date=20240915T231110, end_date=20240915T231110
[2024-09-15 20:11:10,420] {standard_task_runner.py:92} ERROR - Failed to execute job 105 for task BRONZE_MSFT ([Errno 13] Permission denied: '/datalake'; 12858)
[2024-09-15 20:11:10,432] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:11:10,441] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:13:33,616] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:13:33,621] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:13:33,621] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:33,621] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:13:33,621] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:13:33,632] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:13:33,634] {standard_task_runner.py:52} INFO - Started process 13462 to run task
[2024-09-15 20:13:33,637] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpoqxl80pq', '--error-file', '/tmp/tmpdchqilsx']
[2024-09-15 20:13:33,637] {standard_task_runner.py:80} INFO - Job 105: Subtask BRONZE_MSFT
[2024-09-15 20:13:33,665] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:13:33,706] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:13:33,707] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/MSFT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:13:33,710] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240117T000000, start_date=20240915T231333, end_date=20240915T231333
[2024-09-15 20:13:33,719] {standard_task_runner.py:92} ERROR - Failed to execute job 105 for task BRONZE_MSFT ([Errno 13] Permission denied: '/Documents'; 13462)
[2024-09-15 20:13:33,730] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:13:33,739] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:18:23,092] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:18:23,097] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [queued]>
[2024-09-15 20:18:23,097] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:23,097] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:18:23,097] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:18:23,107] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_MSFT> on 2024-01-17 00:00:00+00:00
[2024-09-15 20:18:23,110] {standard_task_runner.py:52} INFO - Started process 14124 to run task
[2024-09-15 20:18:23,112] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_MSFT', 'scheduled__2024-01-17T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmp4yqi4gon', '--error-file', '/tmp/tmpp49sd24t']
[2024-09-15 20:18:23,113] {standard_task_runner.py:80} INFO - Job 105: Subtask BRONZE_MSFT
[2024-09-15 20:18:23,141] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_MSFT scheduled__2024-01-17T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:18:23,181] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_MSFT
AIRFLOW_CTX_EXECUTION_DATE=2024-01-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-17T00:00:00+00:00
[2024-09-15 20:18:27,530] {history.py:244} ERROR - $MSFT: possibly delisted; no price data found  (1h 2024-01-14 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1705208400, endDate = 1704258000")
[2024-09-15 20:18:27,537] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:18:27,546] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_MSFT, execution_date=20240117T000000, start_date=20240915T231823, end_date=20240915T231827
[2024-09-15 20:18:27,563] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:18:27,573] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
