[2024-09-15 20:03:24,053] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:03:24,057] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:03:24,057] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:24,057] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:03:24,057] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:03:24,068] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:03:24,070] {standard_task_runner.py:52} INFO - Started process 11315 to run task
[2024-09-15 20:03:24,073] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpcfpxry7a', '--error-file', '/tmp/tmpnz8n6n_a']
[2024-09-15 20:03:24,073] {standard_task_runner.py:80} INFO - Job 31: Subtask BRONZE_GOOG
[2024-09-15 20:03:24,100] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:03:24,136] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:03:27,917] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-08 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704690000, endDate = 1704258000")
[2024-09-15 20:03:27,925] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:03:27,932] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240109T000000, start_date=20240915T230324, end_date=20240915T230327
[2024-09-15 20:03:27,953] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:03:27,967] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:06:23,954] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:06:23,959] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:06:23,959] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:23,959] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:06:23,959] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:06:23,969] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:06:23,971] {standard_task_runner.py:52} INFO - Started process 12033 to run task
[2024-09-15 20:06:23,974] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpt1k4401e', '--error-file', '/tmp/tmppflhxlht']
[2024-09-15 20:06:23,974] {standard_task_runner.py:80} INFO - Job 33: Subtask BRONZE_GOOG
[2024-09-15 20:06:24,003] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:06:24,042] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:06:24,043] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/datalake'
[2024-09-15 20:06:24,046] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240109T000000, start_date=20240915T230623, end_date=20240915T230624
[2024-09-15 20:06:24,054] {standard_task_runner.py:92} ERROR - Failed to execute job 33 for task BRONZE_GOOG ([Errno 13] Permission denied: '/datalake'; 12033)
[2024-09-15 20:06:24,066] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:06:24,075] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:09:25,990] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:09:25,995] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:09:25,996] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:25,996] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:09:25,996] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:09:26,008] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:09:26,010] {standard_task_runner.py:52} INFO - Started process 12626 to run task
[2024-09-15 20:09:26,012] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmph6p5k5tr', '--error-file', '/tmp/tmpj_8r6ghq']
[2024-09-15 20:09:26,013] {standard_task_runner.py:80} INFO - Job 82: Subtask BRONZE_GOOG
[2024-09-15 20:09:26,042] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:09:26,085] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:09:29,206] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-06 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704517200, endDate = 1704258000")
[2024-09-15 20:09:29,208] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:09:29,212] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240109T000000, start_date=20240915T230925, end_date=20240915T230929
[2024-09-15 20:09:29,239] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:09:29,251] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:12:59,672] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:12:59,677] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:12:59,677] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:59,677] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:12:59,677] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:12:59,688] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:12:59,691] {standard_task_runner.py:52} INFO - Started process 13253 to run task
[2024-09-15 20:12:59,693] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpa1rv8v1n', '--error-file', '/tmp/tmpi2i2v9rt']
[2024-09-15 20:12:59,694] {standard_task_runner.py:80} INFO - Job 82: Subtask BRONZE_GOOG
[2024-09-15 20:12:59,721] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:12:59,760] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:12:59,761] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake/GOOG'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby/datalake'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Documents/airflow_celeby'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/decorators/base.py", line 179, in execute
    return_value = super().execute(context)
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/kaiwang/Documents/airflow_celeby/venv/lib/python3.10/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/kaiwang/Documents/airflow_celeby/dags/get_stocks.py", line 21, in get_history
    (Path(file_path).parent).mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1179, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.10/pathlib.py", line 1175, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/Documents'
[2024-09-15 20:12:59,763] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240109T000000, start_date=20240915T231259, end_date=20240915T231259
[2024-09-15 20:12:59,772] {standard_task_runner.py:92} ERROR - Failed to execute job 82 for task BRONZE_GOOG ([Errno 13] Permission denied: '/Documents'; 13253)
[2024-09-15 20:12:59,786] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-09-15 20:12:59,795] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-15 20:16:25,617] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:16:25,621] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [queued]>
[2024-09-15 20:16:25,621] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:25,621] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-09-15 20:16:25,621] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-09-15 20:16:25,633] {taskinstance.py:1377} INFO - Executing <Task(_PythonDecoratedOperator): BRONZE_GOOG> on 2024-01-09 00:00:00+00:00
[2024-09-15 20:16:25,635] {standard_task_runner.py:52} INFO - Started process 13908 to run task
[2024-09-15 20:16:25,637] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'BRONZER_GET_STONCKS', 'BRONZE_GOOG', 'scheduled__2024-01-09T00:00:00+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/get_stocks.py', '--cfg-path', '/tmp/tmpzy5p44xs', '--error-file', '/tmp/tmpz3wwd6h8']
[2024-09-15 20:16:25,638] {standard_task_runner.py:80} INFO - Job 82: Subtask BRONZE_GOOG
[2024-09-15 20:16:25,665] {task_command.py:370} INFO - Running <TaskInstance: BRONZER_GET_STONCKS.BRONZE_GOOG scheduled__2024-01-09T00:00:00+00:00 [running]> on host kaiwang.
[2024-09-15 20:16:25,704] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=BRONZER_GET_STONCKS
AIRFLOW_CTX_TASK_ID=BRONZE_GOOG
AIRFLOW_CTX_EXECUTION_DATE=2024-01-09T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-01-09T00:00:00+00:00
[2024-09-15 20:16:30,160] {history.py:244} ERROR - $GOOG: possibly delisted; no price data found  (1h 2024-01-06 -> 2024-01-03) (Yahoo error = "Invalid input - start date cannot be after end date. startDate = 1704517200, endDate = 1704258000")
[2024-09-15 20:16:30,162] {python.py:173} INFO - Done. Returned value was: None
[2024-09-15 20:16:30,169] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=BRONZER_GET_STONCKS, task_id=BRONZE_GOOG, execution_date=20240109T000000, start_date=20240915T231625, end_date=20240915T231630
[2024-09-15 20:16:30,199] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-09-15 20:16:30,214] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
